name: SpotDL Automation

on:
  workflow_dispatch:

jobs:
  download-song:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install spotdl

    - name: Create output directory
      run: mkdir -p downloads

    - name: Run SpotDL script
      run: python main.py "https://open.spotify.com/intl-es/track/7CkJfQByYyFdu9jRRXk858"

    - name: Upload downloaded songs
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-songs
        path: downloads/
