name: Spotify Download

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install -U yt-dlp  # Actualiza yt-dlp

    - name: Run script
      run: |
        set -o pipefail
        python main.py 2>&1 | tee error_log.txt

    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error_log.txt
