name: SpotDL Download

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: "URL de Spotify del track"
        required: true
        default: "https://open.spotify.com/intl-es/track/7CkJfQByYyFdu9jRRXk858"

jobs:
  download-spotify-track:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install SpotDL and FFmpeg
        run: |
          pip install spotdl
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Track
        run: |
          spotdl "${{ github.event.inputs.spotify_url }}"
